name: Config
description: 'A simple load config (with multiple json, xml or csv file)'
author:
  name: Syncano
  email: hello@syncano.io
endpoints:
  get:
    POST:
      file: scripts/get.js
      description: Get simply a config with few json file
  multiple:
    POST:
      file: scripts/multiple.js
      description: Get a multiple config with define some key
  load:
    POST:
      file: scripts/load.js
      description: Load a config of config's file...
